services:
  - type: web
    name: vendecerca-front
    runtime: node
    rootDir: client
    buildCommand: pnpm install --frozen-lockfile && pnpm build
    startCommand: pnpm start
    envVars:
      - key: VITE_API_URL
        value: https://vendecercaapi.onrender.com/api/v1/
